### PR TITLE
Additions to the file createMap.php

### PR DESCRIPTION
**Pull request by adri326**

### CODE REVIEW

**Comment by adri326** [comment]
**Do not merge** for now

**Comment by TropicSapling** [comment]
Btw this has conflicts for some reason? Is that why not to merge?

**Comment by adri326** [comment]
I'm making something big in multiple part, and I commited after creating this branch

**Comment by adri326** [comment]
Hmm... you're right, there are conflicts... I need to fix this

**Comment by TropicSapling** [comment]
Well conflicts are created when editing the same file, which means that you've edited the same file in both `master` and `createMap-addition`. So you need to figure out what file it is and fix it :)

**Comment by adri326** [comment]
I'll force the merging then, but I didn't finished my changes

**Comment by TropicSapling** [comment]
No you have to do it with cmd line, the reason for this problem is that you have updated 2 files both on master and createMap-addition. So you'll need to do some special cmds on the cmd line, which might be a bit annoying :confused:

**Comment by adri326** [comment]
Can't I just copy the files from this branch, then paste them in the main branch through GitHub desktop?

**Comment by TropicSapling** [comment]
No, conflicts means the **same** files have been edited on both branches. So you need to choose which changes to keep

**Comment by TropicSapling** [comment]
Delete branch?

**Comment by adri326** [comment]
Yeah

**Pull request merged**
